application:
   blockstackNamesIndex: /var/index/dapps
   domains:
      -  domain: radicle.art

---

spring:
    profiles: test
application:

---

spring:
    profiles: docker-dev
application:

---

spring:
    profiles: staging
application:

---

spring:
    profiles: production
application:
