application:
   blockstackNamesIndex: /var/index/dapps
   mongoIp: localhost
   domains:
      -  domain: radicle.art

---

spring:
    profiles: test
application:
   mongoIp: localhost

---

spring:
    profiles: docker-dev
application:
   mongoIp: localhost

---

spring:
    profiles: staging
application:
   mongoIp: 139.162.204.44

---

spring:
    profiles: production
application:
   mongoIp: 178.79.138.62
