application:
   blockstackNamesIndex: /var/index/dapps
   blockstackOrgBase: https://core-staging.brightblock.org
   artMarketIndex: /var/index/artmarket
   auctionIndex: /var/index/auction

---

spring:
    profiles: test
application:
   blockstackBase: http://localhost:6270
   domains:
      -  domain: www.brightblock.org
         indexFiles: 
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: app.graphitedocs.com
         fields:
            - title
            - description

---

spring:
    profiles: docker-dev
application:
   blockstackBase: https://core-staging.brightblock.org
   domains:
      -  domain: localhost
         indexFiles: 
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: /transit8.com
         indexFiles: 
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description

---

spring:
    profiles: staging
application:
   blockstackBase: https://core-staging.brightblock.org
   domains:
      -  domain: staging.transit8.com
         indexFiles: 
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: /transit8.com
         indexFiles: 
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description

---

spring:
    profiles: production
application:
   blockstackBase: https://core.brightblock.org
   domains:
      -  domain: www.transit8.com
         indexFiles: 
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
      -  domain: /transit8.com
         indexFiles: 
            - indexFileName: records_v01.json
              indexObjType: artwork
            - indexFileName: auctions_v01.json
              indexObjType: auction
         fields:
            - title
            - description
